# The Xcode project and scheme. The app's name as people see it is APP_NAME (below).
PROJECT = pass
SCHEME = pass
# The .noindex suffix keeps Spotlight from indexing (and offering) the build products.
BUILD_DIR = build.noindex
# The product's file name is PRODUCT_NAME (Pass), whatever APP_NAME is.
IOS_PRODUCT = $(BUILD_DIR)/Build/Products/Release-iphoneos/Pass.app
SIM_PRODUCT = $(BUILD_DIR)/Build/Products/Debug-iphonesimulator/Pass.app
# GopenPGP, built from source with Go (scripts/gopenpgp_build.sh); the project links it.
GOPENPGP = go/dist/Gopenpgp.xcframework

# Use the full Xcode even though xcode-select points at the Command Line Tools.
export DEVELOPER_DIR ?= /Applications/Xcode.app/Contents/Developer

# Simulators created by `make sim-create`.
SIM_IPHONE = Pass iPhone
SIM_IPHONE_TYPE = com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro
SIM_IPAD = Pass iPad
SIM_IPAD_TYPE = com.apple.CoreSimulator.SimDeviceType.iPad-Pro-13-inch-M4-8GB

# Personal settings: TEAM, BUNDLE_ID, APP_NAME, PAID_ACCOUNT, DEVICE_<name>. See
# local.mk.example.
BUNDLE_ID = com.example.passforios
# The app's name on the Home Screen and in the AutoFill settings.
APP_NAME = Pass
PAID_ACCOUNT = 0
-include local.mk
# The names of all devices with a UDID, sorted.
MY_DEVICES := $(sort $(foreach v,$(filter DEVICE_%,$(.VARIABLES)),$(if $(strip $($(v))),$(v:DEVICE_%=%))))
ifdef TEAM
SIGNING = -allowProvisioningUpdates
else
SIGNING = CODE_SIGN_IDENTITY=-
endif
# App Groups, AutoFill, Siri, and NFC need a paid Apple Developer Program membership.
# Deferred, so that a target can switch them off with a target-specific PAID_ACCOUNT = 0:
# Xcode's provisioning step sees only the xcconfig files, not command-line overrides.
PASS_PAID_ACCOUNT = $(if $(filter 1,$(PAID_ACCOUNT)),YES,NO)
# Simulator builds sign to run locally: no provisioning profile, entitlements still apply.
SIM_SIGNING = CODE_SIGN_IDENTITY=-
# The upstream App Store app's bundle id. Only upstream's team can sign it, but a build
# with it must never reach a device that has the App Store app and its data.
UPSTREAM_BUNDLE_ID = me.mssun.passforios

# The package plugins (SwiftLint) and macros would otherwise need approval in Xcode first.
XCODEBUILD = xcodebuild -quiet -project $(PROJECT).xcodeproj -scheme $(SCHEME) -derivedDataPath $(BUILD_DIR) \
	-skipPackagePluginValidation -skipMacroValidation
LOCAL_XCCONFIG = Config/Local.xcconfig
ARGS ?=

all: build-sim  ## Build the app for the simulator

help:  ## Show this help
	@grep -hE '^[a-zA-Z_-]+:.*## ' $(MAKEFILE_LIST) | awk -F ':.*## ' '{printf "%-16s %s\n", $$1, $$2}'

# Writes the personal settings from local.mk where both xcodebuild and the Xcode GUI see them.
# The file is only rewritten when its content changes, so it does not trigger rebuilds.
$(LOCAL_XCCONFIG): FORCE hooks
	@printf '%s\n' '// Generated by `make` from local.mk; do not edit.' \
		'PASS_BUNDLE_ID = $(BUNDLE_ID)' \
		'PASS_APP_NAME = $(APP_NAME)' \
		'DEVELOPMENT_TEAM = $(TEAM)' \
		'PASS_PAID_ACCOUNT = $(PASS_PAID_ACCOUNT)' > $@.tmp
	@if cmp -s $@.tmp $@; then rm $@.tmp; else mv $@.tmp $@; echo "Wrote $@"; fi

secrets: $(LOCAL_XCCONFIG)  ## Write Config/Local.xcconfig from local.mk

# The git hooks that keep personal information out of commits and pushes (CLAUDE.md,
# "Personal information"). Every target that writes Config/Local.xcconfig installs them.
hooks:  ## Install the git hooks in .githooks
	@[ "$$(git config core.hooksPath)" = .githooks ] || { git config core.hooksPath .githooks && echo "Installed the git hooks in .githooks"; }

check-private: hooks  ## Check every tracked file for personal information
	@.githooks/check-private tree && echo "No personal information in the tracked files"

$(GOPENPGP):
	rm -rf go/checkout
	./scripts/gopenpgp_build.sh

gopenpgp: $(GOPENPGP)  ## Build the GopenPGP framework with Go (once; `make clean-go` to rebuild)

build-sim: $(LOCAL_XCCONFIG) $(GOPENPGP) sim-create  ## Build the Debug app for the iPhone simulator
	$(XCODEBUILD) -configuration Debug -destination 'platform=iOS Simulator,name=$(SIM_IPHONE)' $(SIM_SIGNING) build

build: $(LOCAL_XCCONFIG) $(GOPENPGP)  ## Build the Release app for any iOS device (no install)
	$(XCODEBUILD) -configuration Release -destination 'generic/platform=iOS' $(SIGNING) build

test: $(LOCAL_XCCONFIG) $(GOPENPGP) sim-create  ## Run the unit tests on the iPhone simulator
	$(XCODEBUILD) -configuration Debug -destination 'platform=iOS Simulator,name=$(SIM_IPHONE)' $(SIM_SIGNING) test

# Writes Config/Local.xcconfig without the paid capabilities; the next other target
# writes it back.
test-free: PAID_ACCOUNT = 0
test-free: $(LOCAL_XCCONFIG) $(GOPENPGP) sim-create  ## Run the unit tests as a build without a paid account (no App Group)
	$(XCODEBUILD) -configuration Debug -destination 'platform=iOS Simulator,name=$(SIM_IPHONE)' $(SIM_SIGNING) test

# Creates a simulator unless one with its name exists. Arguments: name, device type.
define sim_create
	@xcrun simctl list devices available | grep -q "$(1) (" || xcrun simctl create "$(1)" $(2)
endef

sim-create:
	$(call sim_create,$(SIM_IPHONE),$(SIM_IPHONE_TYPE))
	$(call sim_create,$(SIM_IPAD),$(SIM_IPAD_TYPE))

define open_devicehub
	@open "$(DEVELOPER_DIR)/../Applications/DeviceHub.app" 2>/dev/null || true
endef

sim: build-sim  ## Build, install, and launch on the iPhone and iPad simulators
	@for sim in "$(SIM_IPHONE)" "$(SIM_IPAD)"; do \
		xcrun simctl boot "$$sim" 2>/dev/null || true; \
		xcrun simctl install "$$sim" "$(SIM_PRODUCT)" && \
		xcrun simctl launch --terminate-running-process "$$sim" $(BUNDLE_ID) $(ARGS); \
	done
	$(open_devicehub)

stop:  ## Quit the app on both simulators
	@for sim in "$(SIM_IPHONE)" "$(SIM_IPAD)"; do \
		xcrun simctl terminate "$$sim" $(BUNDLE_ID) 2>/dev/null && echo "Stopped on $$sim" || true; \
	done

# The app's files in a simulator (the App Group container with a paid account, else the
# app's own), to inspect the cloned repository, the database, and the defaults.
sim-container:  ## Print the app's data container on the iPhone simulator
	@xcrun simctl get_app_container "$(SIM_IPHONE)" $(BUNDLE_ID) $(if $(filter YES,$(PASS_PAID_ACCOUNT)),group.$(BUNDLE_ID),data)

screenshots:  ## Save screenshots of both simulators to build.noindex/screenshots/
	@mkdir -p $(BUILD_DIR)/screenshots
	@for sim in "$(SIM_IPHONE)" "$(SIM_IPAD)"; do \
		out="$(BUILD_DIR)/screenshots/$$(echo $$sim | tr ' ' '-')-$$(date +%H%M%S).png"; \
		xcrun simctl io "$$sim" screenshot "$$out" >/dev/null && echo "$$out"; \
	done

sim-logs:  ## Stream the log of the app on the iPhone simulator
	xcrun simctl spawn "$(SIM_IPHONE)" log stream --style compact --level debug --predicate 'process == "Pass"'

# The iPad app, unmodified, on this Mac (Apple silicon's "Designed for iPad"). iOS builds
# cannot be signed ad hoc, so this needs TEAM, with this Mac registered in the team's
# devices (-allowProvisioningDeviceRegistration). macOS runs an iOS app only from a wrapper
# bundle (Wrapper/Pass.app and a WrappedBundle link), as Xcode's Run and the App Store
# install them. Its data is its own, apart from the simulators' and devices'.
MAC_PRODUCT = $(BUILD_DIR)/Build/Products/Debug-iphoneos/Pass.app
MAC_WRAPPER = $(BUILD_DIR)/mac/$(APP_NAME).app

mac: $(LOCAL_XCCONFIG) $(GOPENPGP)  ## Build and launch the iPad app on this Mac ("Designed for iPad")
	$(check_team)
	$(XCODEBUILD) -configuration Debug -destination 'platform=macOS,arch=arm64,variant=Designed for iPad' \
		-allowProvisioningUpdates -allowProvisioningDeviceRegistration build
	@# Quits a running copy by bundle id: another iOS app named Pass (the App Store's) may run too.
	@pid=$$(lsappinfo info -only pid "$$(lsappinfo find bundleID=$(BUNDLE_ID))" 2>/dev/null | sed -nE 's/.*"?pid"? ?= ?([0-9]+).*/\1/p'); \
		if [ -n "$$pid" ]; then kill "$$pid" && sleep 1; fi
	@rm -rf "$(BUILD_DIR)/mac" && mkdir -p "$(MAC_WRAPPER)/Wrapper"
	@ditto "$(MAC_PRODUCT)" "$(MAC_WRAPPER)/Wrapper/Pass.app"
	@ln -s Wrapper/Pass.app "$(MAC_WRAPPER)/WrappedBundle"
	open "$(MAC_WRAPPER)" $(if $(ARGS),--args $(ARGS))

define check_team
	@test -n "$(TEAM)" || { echo "ERROR: set TEAM in local.mk"; exit 1; }
	@test "$(BUNDLE_ID)" != "$(UPSTREAM_BUNDLE_ID)" || { echo "ERROR: BUNDLE_ID is the App Store app's; set your own in local.mk"; exit 1; }
endef

# Device builds: -allowProvisioningDeviceRegistration registers the device with the team
# and creates its provisioning profile (valid for a year with a paid membership, 7 days
# with a free team). The app installs next to the App Store app (another bundle id, another
# team), with its own data; it cannot read or change the App Store app's.
# Argument: a device name from local.mk.
define device_install
	$(check_team)
	@udid='$(strip $(DEVICE_$(1)))'; \
	test -n "$$udid" || { echo "ERROR: no device named '$(1)': add DEVICE_$(1) = <UDID> to local.mk ('make devices' lists them)"; exit 1; }; \
	echo "== $(1) ($$udid)"; \
	$(XCODEBUILD) -configuration Release -destination "platform=iOS,id=$$udid" \
		-allowProvisioningUpdates -allowProvisioningDeviceRegistration build || exit 1; \
	xcrun devicectl device install app --device "$$udid" "$(IOS_PRODUCT)" || exit 1; \
	xcrun devicectl device process launch --terminate-existing --device "$$udid" "$(BUNDLE_ID)" $(if $(ARGS),-- $(ARGS)) \
		|| echo "WARNING: installed on $(1), but it did not launch (unlock it and open the app)"
endef

device: $(LOCAL_XCCONFIG) $(GOPENPGP)  ## Build, install, and launch on one device: make device D=<name from local.mk>
	@test -n "$(D)" || { echo "ERROR: name a device: make device D=<name> (one of: $(or $(MY_DEVICES),none set in local.mk))"; exit 1; }
	$(call device_install,$(D))

iphone:  ## make device D=iphone
ipad:  ## make device D=ipad
iphone ipad: $(LOCAL_XCCONFIG) $(GOPENPGP)
	$(call device_install,$@)

# The physical devices this Mac knows, with the name each has in local.mk.
devices:  ## List your devices, their UDIDs, and their names in local.mk
	@pairs='$(foreach n,$(MY_DEVICES),$(n)=$(strip $(DEVICE_$(n))))'; \
	xcrun devicectl list devices --filter "Reality = 'physical'" --columns Platform | { \
		read -r header; echo "$$header   local.mk"; \
		read -r rule; echo "$$rule   --------"; \
		while IFS= read -r line; do \
			name=; for pair in $$pairs; do case "$$line" in *"$${pair#*=}"*) name=$${pair%%=*};; esac; done; \
			echo "$$line   $$name"; \
		done; }

# Which apps a device has with "pass" in their bundle id: the App Store app
# (me.mssun.passforios) and this build (BUNDLE_ID) are separate entries.
device-apps:  ## List the Pass apps installed on a device: make device-apps D=<name>
	@udid='$(strip $(DEVICE_$(D)))'; test -n "$$udid" || { echo "ERROR: make device-apps D=<name>"; exit 1; }; \
	xcrun devicectl device info apps --device "$$udid" --include-all-apps 2>/dev/null | grep -i pass || echo "No Pass apps on $(D)"

console:  ## Relaunch the app on a device and stream its console output: make console D=<name>
	@udid='$(strip $(DEVICE_$(D)))'; test -n "$$udid" || { echo "ERROR: make console D=<name>"; exit 1; }; \
	xcrun devicectl device process launch --terminate-existing --console --device "$$udid" "$(BUNDLE_ID)" $(if $(ARGS),-- $(ARGS))

skills:  ## Export Apple's Xcode agent skills into .claude/skills (git-ignored)
	xcrun agent skills export --output-dir .claude/skills --replace-existing

mcp:  ## Connect Claude Code to Xcode's MCP bridge (enable it in Xcode > Settings > Intelligence first)
	claude mcp add --transport stdio xcode -- env DEVELOPER_DIR=$(DEVELOPER_DIR) xcrun mcpbridge

xcode: $(LOCAL_XCCONFIG)  ## Open the project in Xcode
	open $(PROJECT).xcodeproj

clean:  ## Remove build artifacts
	rm -rf $(BUILD_DIR)

clean-go:  ## Remove the GopenPGP build (`make gopenpgp` rebuilds it)
	rm -rf go

FORCE:

.PHONY: all help secrets hooks check-private gopenpgp build-sim build test test-free sim-create sim stop sim-container screenshots sim-logs \
	mac device iphone ipad devices device-apps console skills mcp xcode clean clean-go FORCE
